development:
    adapter: mysql
    encoding: utf8
    database: sample_app_development
    pool: 5
    username: root
    password:

test:
    adapter: mysql
    encoding: utf8
    database: sample_app_test
    pool: 5
    username: root
    password:

production:
    adapter: mysql
    encoding: utf8
    database: sample_app_production
    pool: 5
    username: root
    password:
